# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artem/Documents/tofino/bmc_updater

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artem/Documents/tofino/bmc_updater

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/Documents/tofino/bmc_updater/CMakeFiles /home/artem/Documents/tofino/bmc_updater//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/Documents/tofino/bmc_updater/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tofino_ver

# Build rule for target.
tofino_ver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tofino_ver
.PHONY : tofino_ver

# fast build rule for target.
tofino_ver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tofino_ver.dir/build.make CMakeFiles/tofino_ver.dir/build
.PHONY : tofino_ver/fast

#=============================================================================
# Target rules for targets named fpga_update

# Build rule for target.
fpga_update: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fpga_update
.PHONY : fpga_update

# fast build rule for target.
fpga_update/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpga_update.dir/build.make CMakeFiles/fpga_update.dir/build
.PHONY : fpga_update/fast

fpga_update.o: fpga_update.c.o

.PHONY : fpga_update.o

# target to build an object file
fpga_update.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpga_update.dir/build.make CMakeFiles/fpga_update.dir/fpga_update.c.o
.PHONY : fpga_update.c.o

fpga_update.i: fpga_update.c.i

.PHONY : fpga_update.i

# target to preprocess a source file
fpga_update.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpga_update.dir/build.make CMakeFiles/fpga_update.dir/fpga_update.c.i
.PHONY : fpga_update.c.i

fpga_update.s: fpga_update.c.s

.PHONY : fpga_update.s

# target to generate assembly for a file
fpga_update.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fpga_update.dir/build.make CMakeFiles/fpga_update.dir/fpga_update.c.s
.PHONY : fpga_update.c.s

tofino_ver.o: tofino_ver.c.o

.PHONY : tofino_ver.o

# target to build an object file
tofino_ver.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tofino_ver.dir/build.make CMakeFiles/tofino_ver.dir/tofino_ver.c.o
.PHONY : tofino_ver.c.o

tofino_ver.i: tofino_ver.c.i

.PHONY : tofino_ver.i

# target to preprocess a source file
tofino_ver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tofino_ver.dir/build.make CMakeFiles/tofino_ver.dir/tofino_ver.c.i
.PHONY : tofino_ver.c.i

tofino_ver.s: tofino_ver.c.s

.PHONY : tofino_ver.s

# target to generate assembly for a file
tofino_ver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tofino_ver.dir/build.make CMakeFiles/tofino_ver.dir/tofino_ver.c.s
.PHONY : tofino_ver.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fpga_update"
	@echo "... tofino_ver"
	@echo "... fpga_update.o"
	@echo "... fpga_update.i"
	@echo "... fpga_update.s"
	@echo "... tofino_ver.o"
	@echo "... tofino_ver.i"
	@echo "... tofino_ver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

